export enum AuthScope {
    IDENTITY = 'identity',
    EDIT = 'edit',
    FLAIR = 'flair',
    HISTORY = 'history',
    MODCONFIG = 'modconfig',
    MODFLAIR = 'modflair',
    MODLOG = 'modlog',
    MODPOSTS = 'modposts',
    MODWIKI = 'modwiki',
    MYSUBREDDITS = 'mysubreddits',
    PRIVATEMESSAGES = 'privatemessages',
    READ = 'read',
    REPORT = 'report',
    SAVE = 'save',
    SUBMIT = 'submit',
    SUBSCRIBE = 'subscribe',
    VOTE = 'vote',
    WIKIEDIT = 'wikiedit',
    WIKIREAD = 'wikiread',
}
